# Generated by Django 3.0.4 on 2021-08-19 19:01

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mobot_client.models.phone_numbers


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0012_drop_country_long_name_restriction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drop',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='dropsession',
            options={'base_manager_name': 'active_sessions'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'base_manager_name': 'active_orders'},
        ),
        migrations.AlterModelOptions(
            name='sku',
            options={'base_manager_name': 'available'},
        ),
        migrations.AlterModelManagers(
            name='dropsession',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('active_sessions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('active_orders', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sku',
            managers=[
                ('available', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='bonuscoin',
            name='drop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_coins', to='mobot_client.Drop'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=mobot_client.models.phone_numbers.PhoneNumberField(db_index=True, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerdroprefunds',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_refunds', to='mobot_client.Customer'),
        ),
        migrations.AlterField(
            model_name='customerdroprefunds',
            name='drop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_refunds', to='mobot_client.Drop'),
        ),
        migrations.AlterField(
            model_name='customerstorepreferences',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_store_preferences', to='mobot_client.Customer'),
        ),
        migrations.AlterField(
            model_name='customerstorepreferences',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_store_preferences', to='mobot_client.Store'),
        ),
        migrations.AlterField(
            model_name='drop',
            name='advertisment_start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='drop',
            name='drop_type',
            field=models.IntegerField(choices=[(0, 'airdrop'), (1, 'item')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='drop',
            name='end_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='drop',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='mobot_client.Item'),
        ),
        migrations.AlterField(
            model_name='drop',
            name='number_restriction',
            field=models.TextField(default='+44'),
        ),
        migrations.AlterField(
            model_name='drop',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='drop',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='mobot_client.Store'),
        ),
        migrations.AlterField(
            model_name='drop',
            name='timezone',
            field=models.TextField(default='UTC'),
        ),
        migrations.AlterField(
            model_name='dropsession',
            name='bonus_coin_claimed',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drop_sessions', to='mobot_client.BonusCoin'),
        ),
        migrations.AlterField(
            model_name='dropsession',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_sessions', to='mobot_client.Customer'),
        ),
        migrations.AlterField(
            model_name='dropsession',
            name='drop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_sessions', to='mobot_client.Drop'),
        ),
        migrations.AlterField(
            model_name='dropsession',
            name='state',
            field=models.IntegerField(choices=[(-4, 'Idle And Refundable'), (-3, 'Idle'), (-2, 'Refunded'), (-1, 'cancelled'), (0, 'ready_to_receive_initial'), (1, 'waiting_for_bonus_tx'), (2, 'waiting_for_size'), (3, 'Waiting For Name'), (4, 'Waiting For Address'), (5, 'Shipping Info Confirmation'), (6, 'Allow Contact Requested'), (7, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mobot_client.Store'),
        ),
        migrations.AlterField(
            model_name='message',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mobot_client.Customer'),
        ),
        migrations.AlterField(
            model_name='message',
            name='direction',
            field=models.PositiveIntegerField(choices=[(0, 'received'), (1, 'sent')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mobot_client.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='drop_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='mobot_client.DropSession'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mobot_client.Sku'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'started'), (1, 'confirmed'), (2, 'shipped'), (3, 'cancelled')], default=0),
        ),
        migrations.AlterField(
            model_name='sku',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='mobot_client.Item'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone_number',
            field=mobot_client.models.phone_numbers.PhoneNumberField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='store',
            name='privacy_policy_url',
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name='sku',
            unique_together={('item', 'identifier')},
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.IntegerField(choices=[(-2, 'refund'), (-1, 'bonus'), (1, 'payment')], db_index=True)),
                ('amount_in_mob', models.DecimalField(db_index=True, decimal_places=6, default=Decimal('0'), max_digits=6, max_length=16)),
                ('direction', models.IntegerField(choices=[(-1, 'to_customer'), (1, 'to_store')], default=1)),
                ('status', models.IntegerField(choices=[(-3, 'not_started'), (-2, 'failure'), (-1, 'no address found for customer'), (0, 'in progress'), (1, 'succeeded'), (2, 'empty because amount in mob was too small to send')], default=-3)),
                ('payment_address', models.TextField(blank=True, null=True)),
                ('drop_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='mobot_client.DropSession')),
            ],
        ),
    ]
