# Generated by Django 3.0.4 on 2021-08-20 20:03

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0013_auto_20210819_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonuscoin',
            options={'base_manager_name': 'available'},
        ),
        migrations.AlterModelManagers(
            name='bonuscoin',
            managers=[
                ('available', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='drop',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='mobot_client.Item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'started'), (1, 'confirmed'), (2, 'shipped'), (3, 'cancelled')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.IntegerField(blank=True, choices=[(-2, 'refund'), (-1, 'bonus'), (1, 'payment')], db_index=True, null=True),
        ),
    ]
