# Generated by Django 3.0.4 on 2021-08-20 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobot_client', '0014_auto_20210820_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonuscoin',
            old_name='number_available',
            new_name='number_available_at_start',
        ),
    ]
